events {}

http {
  server_tokens off;

  server {
    listen 8080;
    server_name trade.mihoservice.xyz;
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $api_upstream api:8000;
    set $frontend_upstream frontend:3000;

    location /api/ {
      proxy_pass http://$api_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-Id $request_id;
    }

    location = /healthz {
      proxy_pass http://$api_upstream/healthz;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-Id $request_id;
    }

    location / {
      proxy_pass http://$frontend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-Id $request_id;
    }
  }
}
